# Generated by Django 3.0.5 on 2020-04-29 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instagram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.URLField(max_length=2000)),
                ('profile_image', models.URLField(max_length=2000)),
                ('user', models.CharField(max_length=100)),
                ('created', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'instagrams',
            },
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=2000)),
                ('size', models.IntegerField()),
            ],
            options={
                'db_table': 'main_pages',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address1', models.CharField(max_length=300)),
                ('address2', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=45)),
                ('phone', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=30)),
                ('store_type', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'stores',
            },
        ),
    ]
