# Generated by Django 3.0.5 on 2020-05-01 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instagram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.URLField(max_length=2000)),
                ('profile_image', models.URLField(max_length=2000)),
                ('user', models.CharField(max_length=100)),
                ('created_at', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'instagrams',
            },
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=2000)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=400)),
                ('hover_description', models.CharField(max_length=400)),
                ('size', models.IntegerField()),
                ('code', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'main_pages',
            },
        ),
        migrations.CreateModel(
            name='StoreType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'store_types',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address1', models.CharField(max_length=300)),
                ('address2', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=45)),
                ('phone', models.CharField(max_length=20)),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=20)),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=20)),
                ('state', models.CharField(max_length=30)),
                ('store_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='foundation.StoreType')),
            ],
            options={
                'db_table': 'stores',
            },
        ),
    ]
