# Generated by Django 3.0.5 on 2020-04-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0002_auto_20200429_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='code',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
