# Generated by Django 3.0.5 on 2020-04-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_sneakers',
            field=models.BooleanField(default=False),
        ),
    ]
