# Generated by Django 3.0.5 on 2020-04-29 02:45

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_is_sneakers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='description',
        ),
        migrations.AlterField(
            model_name='detail',
            name='information',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.CharField(max_length=500, null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Product')),
            ],
            options={
                'db_table': 'descriptions',
            },
        ),
    ]
